language: python
python:
  - "2.7"
#   - "3.4"  # TODO: The anaconda mro_base package seems to be broken. Re-enable when fixed.
  - "3.5"
  - "3.6"

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install -c r r r-knitr
install:
  - pip install pycodestyle
  - pip install .[all]

# Cache isn't working yet because problems with expiration header. Disable for now because it's breaking builds.
# cache: pip

script:
  - bash run_tests.sh

# Deploy to pypi automatically from tagged releases on the stable branch
deploy:
  provider: pypi
  user: nikkiray
  password:
   secure: cpt5gMiDQa8kMObs+sCAlRl9y1Q9Ii5CKefwMP9NuJpCZVMJm6SI4lp89kPdGCBp8fl4EW6pWzHHpuLIsN7zsIl/NVzzsWHmuowt8ss1c2Yqd7Oygh91p0ZEN9jFJmWnw83bke3/FLQnz0LldWjG/FQwC0MeuRzsw79uhcj7Qe7XC0WASA+7i4aGWu9VrpQUW8EoN+MK3T5KZwXI9qWF6dHcwvLVjoHq1voKfJY1ZYjB13nIvZaXlTF1PqjovTL24BXebUGlQ+EcMe5nRTZt0w9SIeSnVgnEZY/leWTQofMkXySKP23M/ZYyEPwCCiMp0im+uKnFl6Tf4Zh7rDmlydgXEVPAsM3vGtQjqLFvGadoRQs6J+3CrB+RxAsJHRC9NEowpJ1T8NgFKBqFU/ECKuke47nZkcdzmFTsoPGuncjaCiN5HtlPyLStjqdwxOUwwXxHDgjPNn6Gud6Nbs49ZTXY52WAx6s9sr1gDWHJKaMQJF4k4/wuDw+oMSqDQZ82d/WitifGb4P+0dWi8YNfBQG4WBpVIOpEnI7t72/VxCcZx0v8cZ1OBXugxXb3I852bkFWPA0b5umWn6CJVxKyS+Hx9aCZvXVvEbBm3LQ/fmunrblN7oj+y50qjKCYgJqR962AjXDYneiUuivuHE4IoZw0QjyQfTjBEb748LJQP+U=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: airbnb/knowledge-repo
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
